---
name: 'JavaScript Code Review'

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ESLint
        run: |
          npm install eslint --global
          eslint --init  # Optional to set up ESLint if not done yet

      - name: Run ESLint
        run: eslint . --fix
...